'use client';
import {useState,useEffect,type FormEvent} from 'react';
import {Heart,Lock,Eye,EyeOff} from 'lucide-react';
import {backend,homeURL} from './config';
export default function Access({activate=false}:{activate?:boolean}){const [token,setToken]=useState(''),[ready,setReady]=useState(!activate),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{if(activate){setToken(new URLSearchParams(window.location.hash.slice(1)).get('activate')||'');window.history.replaceState(null,'',window.location.pathname+window.location.search);setReady(true)}},[activate]);async function submit(e:FormEvent){e.preventDefault();setError('');if(activate&&password!==confirm){setError('两次输入的密码不一致。');return}setBusy(true);try{const s=backend();
if(activate){const check=await fetch(import.meta.env.VITE_SUPABASE_URL+'/auth/v1/settings',{headers:{apikey:import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY},signal:AbortSignal.timeout(15000)});if(!check.ok)throw new Error('小家暂时连接不上，请稍后重试。');const settings=await check.json();if(settings.disable_signup||!settings.mailer_autoconfirm)throw new Error('小家的邀请设置尚未完成，请联系邀请你的人。');}
const {data,error:authError}=activate?await s.auth.signUp({email,password,options:{data:{name,invitation:token}}}):await s.auth.signInWithPassword({email,password});
if(authError)throw new Error(activate?'激活未完成：邀请可能已失效、邮箱已使用，或连接暂时中断。请联系邀请你的人。':'邮箱或密码不正确，或连接暂时中断，请重试。');
if(!data.session)throw new Error('账号已创建，但尚未完成登录。请联系建站的人检查邮箱确认设置；不要反复激活。');
window.location.assign(homeURL())}catch(e){setError((e as Error).message);setBusy(false)}}return <main className="access-screen"><div className="access-story"><div className="access-brand"><Heart size={25} fill="currentColor"/> 与你</div><p className="eyebrow">OUR LITTLE HOME</p><h1>世界很大，<br/>这里刚好住下我们。</h1><img src="./pet.webp" alt="小猫糯米在等你回家"/><p>把回忆、心愿和想念，<br/>留在只有我们能打开的小家。</p></div><section className="access-card"><span className="eyebrow"><Lock size={14}/> JUST THE TWO OF US</span><h2>{activate?'给你一把小家的钥匙':'欢迎回家。'}</h2><p className="access-intro">{activate?'设置你自己的登录账号和密码。':'用小家的邮箱账号和密码登录。'}<br/>不需要注册其他平台账号。</p>{ready&&activate&&!token?<div className="form-error">请从完整的专属激活链接进入。已经激活？<a href="./">去登录</a></div>:<form className="form" onSubmit={submit}>{activate&&<label>你的昵称<input autoComplete="nickname" maxLength={20} value={name} onChange={e=>setName(e.target.value)} required placeholder="我们怎么称呼你"/></label>}<label>登录邮箱<input type="email" autoComplete="username" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} required placeholder="你的常用邮箱"/></label><label>密码<div className="password-field"><input type={show?'text':'password'} autoComplete={activate?'new-password':'current-password'} minLength={activate?10:undefined} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} required placeholder={activate?'至少 10 个字符':'输入你的小家密码'}/><button type="button" aria-label={show?'隐藏密码':'显示密码'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{activate&&<label>再输入一次密码<input type={show?'text':'password'} autoComplete="new-password" minLength={10} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>}{error&&<p role="alert" className="form-error">{error}</p>}<button className="btn form-submit" disabled={busy||!ready}>{busy?'正在开门…':activate?'设置好，回家':'进入我们的小家'}</button></form>}<p className="access-help">{activate?'激活链接仅可使用一次。邮箱用作登录账号，不会发送邮件。':'首次使用，请打开专属激活链接。此处不开放自由注册。'}</p>{activate&&<a className="text-btn" href="./">已有账号，直接登录</a>}</section></main>}
