'use client';
import {useState,useEffect,useCallback, type FormEvent} from 'react';
import {Heart,House,Camera,Mail,PawPrint,Plus,Settings,Lock,MapPin,Check,Trash2,Pencil,CalendarDays,Sparkles,Utensils,Hand,Volleyball,RefreshCw,BookHeart,ImagePlus,X} from 'lucide-react';
import {differenceInCalendarDays,addYears,parseISO,format} from 'date-fns';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import AccountControls from './account-controls';
import {homeRequest} from './api';
import {homeURL} from './config';
import Photo from './Photo';
type Kind='memory'|'wish'|'letter';
type Item={id:string;kind:Kind;title:string;body:string;day:string;image:string;completed:number;unlock_at:number;author:string;created_at:number;sealed:number};
type State={settings:{start_date:string;name_a:string;name_b:string;pet_name:string};members:{slot:number;user_id:string;nickname:string}[];records:Item[];replies:{id:string;record_id:string;body:string;author:string;created_at:number}[];pet:{action:string;last_at:number;total:number}[];me:string;hasPartner:boolean;serverTime:number};
type Draft={id?:string;kind:Kind;title:string;body:string;day:string;image:string;completed:boolean;unlock:string};
const today=()=>new Date(Date.now()+8*3600000).toISOString().slice(0,10);

const labels={memory:'回忆',wish:'心愿',letter:'信件'};
const sections=[{id:'home',name:'我们的小家',Icon:House},{id:'memory',name:'时光轴',Icon:Camera},{id:'wish',name:'共同心愿',Icon:Heart},{id:'letter',name:'留给你的话',Icon:Mail},{id:'pet',name:'宠物小屋',Icon:PawPrint}];
export default function Home(){
const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('home'),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[file,setFile]=useState<File|null>(null),[localImage,setLocalImage]=useState(''),[deleteId,setDeleteId]=useState<string|null>(null),[detailId,setDetailId]=useState<string|null>(null),[reply,setReply]=useState(''),[settings,setSettings]=useState(false),[settingsDraft,setSettingsDraft]=useState({start_date:'',name_a:'我',name_b:'你',pet_name:'糯米',nickname:''}),[petAction,setPetAction]=useState(''),[now,setNow]=useState(Date.now());
const reload=useCallback(async()=>{try{const r=await homeRequest('/api/home',{cache:'no-store'});if(r.status===401){window.location.assign(homeURL());return}const j=await r.json() as State & {error?:string;id:string};if(!r.ok)throw new Error(j.error||'暂时无法读取。');setData(j);setError('');setNow(j.serverTime)}catch(e){setError((e as Error).message)}},[]);
useEffect(()=>{reload();const t=setInterval(()=>{if(document.visibilityState==='visible')reload()},30000);return()=>clearInterval(t)},[reload]);
useEffect(()=>{if(!file){setLocalImage('');return}const url=URL.createObjectURL(file);setLocalImage(url);return()=>URL.revokeObjectURL(url)},[file]);
async function mutate(p:Record<string,unknown>){const r=await homeRequest('/api/home',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const j=await r.json() as State & {error?:string;id:string};if(!r.ok)throw new Error(j.error||'保存失败，请稍后重试。');setData(j);setError('');setNow(j.serverTime);return j;}
function openNew(kind:Kind){setDraft({kind,title:'',body:'',day:today(),image:'',completed:false,unlock:''});setFile(null);setFormError('')}
function edit(item:Item){setDraft({...item,completed:!!item.completed,unlock:item.unlock_at>Date.now()?new Date(item.unlock_at+8*3600000).toISOString().slice(0,16):''});setFile(null);setFormError('');setDetailId(null)}
function openSettings(){if(data)setSettingsDraft({...data.settings,nickname:data.members.find(m=>m.user_id===data.me)?.nickname||''});setFormError('');setSettings(true)}
async function save(e:FormEvent){e.preventDefault();if(!draft)return;setBusy(true);setFormError('');try{let image=draft.image;if(file){const r=await homeRequest('/api/photo',{method:'POST',headers:{'Content-Type':file.type},body:file});const j=await r.json() as State & {error?:string;id:string};if(!r.ok)throw new Error(j.error);image=j.id;setDraft(d=>d?{...d,image}:d);setFile(null)}const unlock=draft.unlock?Date.parse(draft.unlock+':00+08:00'):0;if(draft.unlock&&unlock<=Date.now())throw new Error('请选择未来的开信时间，或者清空时间立即送出。');await mutate({action:'save',...draft,image,unlock_at:unlock});setDraft(null);toast.success(draft.kind==='letter'&&unlock?'信已封好，等那天一起打开。':'已经收藏进我们的小家。')}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
async function saveSettings(e:FormEvent){e.preventDefault();setBusy(true);setFormError('');try{await mutate({action:'settings',...settingsDraft});setSettings(false);toast.success('小家的资料已更新。')}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
async function action(p:Record<string,unknown>,message:string){setBusy(true);try{await mutate(p);toast.success(message);return true}catch(e){toast.error((e as Error).message);return false}finally{setBusy(false)}}
async function pet(kind:string){if(await action({action:'pet',kind},{feed:'吃饱啦，想靠着你打个盹。',play:'今天也有好好陪我玩！',pat:'呼噜呼噜……喜欢你的摸摸。'}[kind]||'好开心！')){setPetAction(kind);setTimeout(()=>setPetAction(''),2200)}}
useEffect(()=>{const c=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!c?.registerTool)return;const ac=new AbortController();try{Promise.resolve(c.registerTool({name:'start_memory_creation',title:'开始记录回忆',description:'打开回忆编辑表单并填入标题；不会保存或上传。',inputSchema:{type:'object',properties:{title:{type:'string',maxLength:80}},required:['title'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const p=input as {title?:unknown};if(!p||typeof p.title!=='string'||p.title.length>80)throw new Error('标题必须是 80 字以内的文字');setDraft({kind:'memory',title:p.title,body:'',day:today(),image:'',completed:false,unlock:''});setFile(null);setFormError('');return {status:'draft_opened',saved:false}}},{signal:ac.signal})).catch(()=>{})}catch{}return()=>ac.abort()},[]);
const author=(id:string)=>{const m=data?.members.find(m=>m.user_id===id);return m?.nickname||(m?.slot===1?data?.settings.name_a:data?.settings.name_b)||'我们'};
const memories=data?.records.filter(x=>x.kind==='memory')||[],wishes=data?.records.filter(x=>x.kind==='wish')||[],letters=data?.records.filter(x=>x.kind==='letter')||[];
const detail=data?.records.find(x=>x.id===detailId);
const since=data?.settings.start_date;const elapsed=since?Math.max(1,differenceInCalendarDays(parseISO(today()),parseISO(since))+1):null;
let anniversary:number|null=null;if(since){const start=parseISO(since),day=parseISO(today());let next=addYears(start,day.getFullYear()-start.getFullYear());if(next<day)next=addYears(start,day.getFullYear()-start.getFullYear()+1);anniversary=differenceInCalendarDays(next,day)}
const stat=(kind:string,hours:number)=>{const v=data?.pet.find(p=>p.action===kind);return v?Math.max(10,Math.round(100-(now-v.last_at)/3600000*(90/hours))):60};
const fullness=stat('feed',24),happiness=Math.max(stat('play',36),stat('pat',18));const interactions=data?.pet.reduce((sum,p)=>sum+p.total,0)||0;
function empty(kind:Kind){const Icon=kind==='memory'?Camera:kind==='wish'?Heart:Mail;return <Empty className={'blank blank-'+kind}><EmptyHeader><EmptyMedia><Icon size={30} strokeWidth={1.2}/></EmptyMedia><EmptyTitle>{kind==='memory'?'第一段故事，从今天开始':kind==='wish'?'把「以后一起」写在这里':'有些话，想慢慢说给你听'}</EmptyTitle><EmptyDescription>{kind==='memory'?'一张照片，一顿晚饭，或一个舍不得忘的小瞬间。':kind==='wish'?'一顿想吃的饭，一座想去的城，一件想一起做的小事。':'现在送出一句想念，或者把一封信留给未来。'}</EmptyDescription></EmptyHeader><button className="btn secondary" onClick={()=>openNew(kind)}><Plus size={16}/>写下第一{kind==='letter'?'封':'条'}{labels[kind]}</button></Empty>}
function petPanel(large=false){return <section className={'pet-card '+(large?'pet-large':'')}><div className="section-heading"><span className="eyebrow"><PawPrint size={15}/> OUR LITTLE FRIEND</span><button className="text-btn" onClick={large?openSettings:()=>setTab('pet')}>{large?'改个名字':'去陪陪它'}</button></div><div className="pet-image-wrap"><img className={'pet-image '+(petAction?'pet-'+petAction:'')} src="./pet.webp" alt="戴着爱心项圈的奶白色小猫"/><span className="pet-bubble" role="status">{petAction==='feed'?'好吃！':petAction==='play'?'再玩一次！':petAction==='pat'?'呼噜呼噜～':'今天也在等你们。'}</span></div><h2>{data?.settings.pet_name||'糯米'}<span> · 我们一起养的小猫</span></h2><div className="pet-stats"><label>饱腹感 <span>{fullness}%</span><Progress value={fullness} aria-label="饱腹感"/></label><label>开心值 <span>{happiness}%</span><Progress value={happiness} aria-label="开心值"/></label></div><div className="pet-buttons"><button disabled={busy} onClick={()=>pet('feed')}><Utensils size={17}/>喂食</button><button disabled={busy} onClick={()=>pet('play')}><Volleyball size={17}/>陪玩</button><button disabled={busy} onClick={()=>pet('pat')}><Hand size={17}/>摸摸</button></div>{large&&<p className="pet-note">已经收到你们的 {interactions} 次照顾 · 亲密等级 Lv.{1+Math.floor(interactions/10)}<br/>饱腹感和开心值会慢慢下降，回来陪陪它就好。</p>}</section>}
function cards(kind:Kind,items:Item[]){return items.length?<div className={'cards '+kind+'-cards'}>{items.map(item=><article className={'entry '+(item.completed?'completed':'')} key={item.id}>{item.image&&<button className="entry-photo" onClick={()=>setDetailId(item.id)} aria-label={'查看'+item.title}><Photo path={item.image} alt={item.title} loading="lazy"/></button>}<div className="entry-content"><div className="entry-meta"><span>{kind==='letter'?(item.sealed?<><Lock size={13}/>等待开启</>:<><Mail size={13}/>可以读啦</>):format(parseISO(item.day),'yyyy.MM.dd')}</span><span>{author(item.author)}</span></div><button className="entry-title" onClick={()=>setDetailId(item.id)}>{item.title}</button>{item.sealed?<p className="muted">{new Date(item.unlock_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'})} 开启</p>:<p className="entry-body">{item.body||'属于我们的小瞬间。'}</p>}<div className="entry-bottom">{kind==='wish'?<label className="check-label"><Checkbox checked={!!item.completed} disabled={busy} onCheckedChange={checked=>action({action:'complete',id:item.id,completed:checked===true},checked?'又一起完成了一件小事！':'心愿已放回待完成。')}/>{item.completed?'我们完成啦':'等待一起完成'}</label>:<button className="text-btn" onClick={()=>setDetailId(item.id)}>{kind==='memory'?'展开回忆':'看看这封信'}</button>}<div className="icon-actions">{!item.sealed&&(kind!=='letter'||item.author===data?.me)&&<button aria-label={'编辑'+item.title} onClick={()=>edit(item)}><Pencil size={15}/></button>}{(kind!=='letter'||item.author===data?.me)&&<button aria-label={'删除'+item.title} onClick={()=>setDeleteId(item.id)}><Trash2 size={15}/></button>}</div></div></div></article>)}</div>:empty(kind)}
return <><Toaster position="top-center"/><Tabs value={tab} onValueChange={setTab} className="app"><header className="topbar"><button className="brand" onClick={()=>setTab('home')} aria-label="回到首页"><span className="brand-icon"><Heart size={22} fill="currentColor"/></span><span>与你<small>OUR LITTLE HOME</small></span></button><TabsList className="navigation" aria-label="小家导航">{sections.map(({id,name,Icon})=><TabsTrigger value={id} key={id}><Icon size={17}/><span>{name}</span></TabsTrigger>)}</TabsList><button className="settings-button" onClick={openSettings} disabled={!data}><Settings size={18}/><span>小家设置</span></button></header><main className="main">
{error&&<div className="error-banner" role="alert">{error}<button onClick={reload}><RefreshCw size={15}/>重试</button></div>}
{!data?<div className="loading"><p>正在打开我们的小家…</p><Skeleton className="h-64 w-full rounded-3xl"/></div>:<>
<TabsContent value="home"><div className="welcome"><div><p className="eyebrow">JUST THE TWO OF US</p><h1>日子很长，<em>我们慢慢收藏。</em></h1><p className="welcome-note">{author(data.me)}，欢迎回家。今天有什么想留住的小事？</p></div><button className="btn" onClick={()=>openNew('memory')}><Plus size={18}/>记录这一刻</button></div>
<div className="home-grid"><div className="home-main"><section className="together-card"><div className="section-heading"><span className="eyebrow">{data.settings.name_a} & {data.settings.name_b}</span><Heart size={21} strokeWidth={1.4}/></div>{elapsed?<><p className="counter-label">这是我们在一起的</p><div className="day-count">{elapsed.toLocaleString()}<span>天</span></div><p className="since">从 {format(parseISO(since!),'yyyy 年 M 月 d 日')}，到每一个明天。</p></>:<><p className="counter-label">故事的第一页</p><h2 className="start-title">我们的「第一天」<br/>是哪一天？</h2><button className="text-btn" onClick={openSettings}>设置恋爱日期 <CalendarDays size={15}/></button></>}<div className="anniversary"><CalendarDays size={18}/><span>{anniversary===null?'记下开始的日期，让每一个纪念日都有迹可循。':anniversary===0?'今天是我们的纪念日，抱抱彼此吧。':<>距离下一个恋爱纪念日，还有 <strong>{anniversary}</strong> 天</>}</span></div></section>
<div className="section-heading recent-title"><h2>最近的小美好 <span>OUR MEMORIES</span></h2><button className="text-btn" onClick={()=>setTab('memory')}>全部回忆</button></div>{cards('memory',memories.slice(0,2))}</div><aside>{petPanel()}<section className="little-note"><Mail size={23} strokeWidth={1.3}/><h3>想念，有一个收件地址。</h3><p>写给今天的你，也写给未来的我们。</p><button className="text-btn" onClick={()=>openNew('letter')}>写一封信 <Pencil size={14}/></button></section></aside></div>
<section className="wish-preview"><div className="section-heading"><h2>下次，一起 <span>OUR WISHLIST</span></h2><button className="text-btn" onClick={()=>openNew('wish')}><Plus size={15}/>添加心愿</button></div>{wishes.filter(w=>!w.completed).length?<div className="wish-strip">{wishes.filter(w=>!w.completed).slice(0,3).map(w=><button key={w.id} onClick={()=>{setTab('wish');setDetailId(w.id)}}><Heart size={18}/><span>{w.title}</span></button>)}</div>:<button className="wish-invitation" onClick={()=>openNew('wish')}><span>去一个没去过的地方，或者一起做顿晚饭。</span><strong>把你们的第一个心愿写在这里 <Plus size={16}/></strong></button>}</section>
</TabsContent>
{(['memory','wish','letter'] as Kind[]).map(kind=><TabsContent value={kind} key={kind}><div className="page-heading"><div><p className="eyebrow">{kind==='memory'?'A LITTLE BIT OF US':kind==='wish'?'THINGS WE WILL DO':'WORDS FOR YOU'}</p><h1>{kind==='memory'?'把我们，留在时光里。':kind==='wish'?'喜欢的事，要一起做。':'有些心里话，只说给你。'}</h1><p className="muted">{kind==='memory'?`${memories.length} 段回忆，都是我们。`:kind==='wish'?`${wishes.length} 个心愿 · 已一起完成 ${wishes.filter(w=>w.completed).length} 个`:'即时留言，或者写给未来的一封信。'}</p></div><button className="btn" onClick={()=>openNew(kind)}><Plus size={18}/>{kind==='memory'?'记录这一刻':kind==='wish'?'添加心愿':'写一封信'}</button></div>{cards(kind,kind==='memory'?memories:kind==='wish'?wishes:letters)}</TabsContent>)}
<TabsContent value="pet"><div className="page-heading"><div><p className="eyebrow">A HOME FOR THREE</p><h1>小小一只，双倍的爱。</h1><p className="muted">你们共同照顾的小伙伴。</p></div></div><div className="pet-room">{petPanel(true)}</div></TabsContent>
</>}
<footer><span><Lock size={13}/>我们的私密空间</span><span>与你一起，把普通日子过成纪念。</span><span>{today().replaceAll('-','.')} · 北京时间</span></footer></main></Tabs>
<Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy){setDraft(null);setFile(null)}}}><DialogContent className="editor-modal"><DialogHeader><DialogTitle>{draft?.id?'编辑':'写下'}{draft?labels[draft.kind]:''}</DialogTitle><DialogDescription>{draft?.kind==='letter'?'选一个未来的时间封存，或留空立即送出。时间以北京时间为准。':'不必是大事，值得记住就好。'}</DialogDescription></DialogHeader>{draft&&<form onSubmit={save} className="form"><label>标题<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} required maxLength={80} placeholder={draft.kind==='wish'?'例如：一起去看海':'给这一刻起个名字'}/></label><label>{draft.kind==='wish'?'计划 / 完成后的回忆':'想说的话'}<textarea rows={5} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} maxLength={5000} required={draft.kind==='letter'} placeholder="慢慢写，我们都在这里。"/></label><div className="form-row"><label>{draft.kind==='wish'?'计划日期':'记录日期'}<input type="date" value={draft.day} onChange={e=>setDraft({...draft,day:e.target.value})} required/></label>{draft.kind==='letter'&&<label>开信时间（可留空）<input type="datetime-local" value={draft.unlock} onChange={e=>setDraft({...draft,unlock:e.target.value})}/></label>}</div>{draft.kind!=='letter'&&<><label className="upload-control"><ImagePlus size={20}/><span>{file?file.name:'添加一张照片'}<small>最大 8 MB，上传时压缩；GIF 保存为静态照片</small></span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size>8*1024*1024){setFormError('照片需小于 8 MB。');e.target.value='';return}setFormError('');setFile(f||null)}}/></label>{(localImage||draft.image)&&<div className="upload-preview">{localImage?<img src={localImage} alt="待保存的照片"/>:<Photo path={draft.image} alt="待保存的照片"/>}<button type="button" aria-label="移除照片" onClick={()=>{setFile(null);setDraft({...draft,image:''})}}><X size={17}/></button></div>}</>}{draft.kind==='wish'&&<label className="check-label"><Checkbox checked={draft.completed} onCheckedChange={v=>setDraft({...draft,completed:v===true})}/>我们已经一起完成了</label>}{draft.kind==='letter'&&draft.unlock&&<p className="form-hint"><Lock size={15}/>封存后，直到约定时间，两个人都不能提前查看正文。</p>}{formError&&<p className="form-error" role="alert">{formError}</p>}<button className="btn form-submit" disabled={busy}>{busy?'正在保存…':draft.kind==='letter'&&draft.unlock?'封好这封信':'保存到小家'}</button></form>}</DialogContent></Dialog>
<Dialog open={settings} onOpenChange={open=>{if(!busy)setSettings(open)}}><DialogContent className="editor-modal"><DialogHeader><DialogTitle>让小家更像我们</DialogTitle><DialogDescription>名字和日期可以随时修改。</DialogDescription></DialogHeader><form onSubmit={saveSettings} className="form"><div className="form-row"><label>你的名字<input maxLength={20} required value={settingsDraft.name_a} onChange={e=>setSettingsDraft({...settingsDraft,name_a:e.target.value})}/></label><label>另一半的名字<input maxLength={20} required value={settingsDraft.name_b} onChange={e=>setSettingsDraft({...settingsDraft,name_b:e.target.value})}/></label></div><label>恋爱开始日期<input type="date" max={today()} value={settingsDraft.start_date} onChange={e=>setSettingsDraft({...settingsDraft,start_date:e.target.value})}/></label><label>我发布记录时的署名<input required maxLength={20} placeholder="你的昵称" value={settingsDraft.nickname} onChange={e=>setSettingsDraft({...settingsDraft,nickname:e.target.value})}/></label><label>小猫的名字<input required maxLength={20} value={settingsDraft.pet_name} onChange={e=>setSettingsDraft({...settingsDraft,pet_name:e.target.value})}/></label><p className="form-hint"><Lock size={16}/>两个人分别使用独立账号和密码登录，记录与照片只在小家内共享。</p>{formError&&<p className="form-error" role="alert">{formError}</p>}<button className="btn form-submit" disabled={busy}>{busy?'正在保存…':'保存我们的小家'}</button><button className="sign-out" type="button" onClick={async()=>{const r=await homeRequest('/api/auth/sign-out',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(r.ok)window.location.assign(homeURL());else toast.error('退出未成功，请重试。')}}>退出当前账号</button></form>{data&&<AccountControls owner={data.members.find(m=>m.user_id===data.me)?.slot===1} hasPartner={data.hasPartner}/>}</DialogContent></Dialog>
<Dialog open={!!detail} onOpenChange={open=>{if(!open){setDetailId(null);setReply('')}}}><DialogContent className="editor-modal"><DialogHeader><DialogTitle>{detail?.title}</DialogTitle><DialogDescription>{detail?`${detail.day} · ${author(detail.author)}`:''}</DialogDescription></DialogHeader>{detail&&<div className="detail">{detail.image&&<Photo className="detail-photo" path={detail.image} alt={detail.title}/>}<div className="detail-text">{detail.sealed?<div className="sealed"><Lock size={32}/><h3>留一点期待给未来。</h3><p>这封信将在 {new Date(detail.unlock_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}（北京时间）开启。</p></div>:detail.body||'这一刻，已经被好好收藏。'}</div>{!detail.sealed&&(detail.kind!=='letter'||detail.author===data?.me)&&<button className="text-btn" onClick={()=>edit(detail)}><Pencil size={15}/>编辑{labels[detail.kind]}</button>}{detail.kind==='memory'&&<div className="perspectives"><h3>也听听你的版本</h3>{data?.replies.filter(r=>r.record_id===detail.id).map(r=><div className="reply" key={r.id}><strong>{author(r.author)}</strong><p>{r.body}</p></div>)}<form onSubmit={async e=>{e.preventDefault();if(await action({action:'reply',id:detail.id,body:reply},'你的这份回忆，也留下了。'))setReply('')}}><label className="sr-only" htmlFor="reply">补充你的回忆</label><textarea id="reply" value={reply} onChange={e=>setReply(e.target.value)} placeholder="那一天，我还记得……" maxLength={1500} required/><button disabled={busy} className="btn secondary">留下我的回忆</button></form></div>}</div>}</DialogContent></Dialog>
<AlertDialog open={!!deleteId} onOpenChange={open=>{if(!open&&!busy)setDeleteId(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除这条记录？</AlertDialogTitle><AlertDialogDescription>删除后，两个人都将看不到这条记录及其补充内容，无法撤销。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>再想想</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(await action({action:'delete',id:deleteId},'记录已删除。')){setDeleteId(null);setDetailId(null)}}}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
</>}
